cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      access-key: AKIASMGHNMVD2QYFLGD3
      secret-key: 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

logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

